/*============================
業務管理シート運用中gas②
============================*/

//var COLUMN_TIME_START = "K";
var COLUMN_TIME_START = "C";
//var COLUMN_TIME_END = "BF";
var COLUMN_TIME_END = "AX";

var INDEX_TIME_START = 3;

var WEEKDAY_MASTER_SHEET_LABRL = "平日マスタ";
var HOLIDAY_MASTER_SHEET_LABRL = "休日マスタ";
var PUBLIC_HOLIDAY_MASTER_SHEET_LABRL = "祝日マスタ";

var COLUMN_NAME = "A";
var COLUMN_START = "B";
var COLUMN_END = "C";
var COLUMN_REST_START = "D";
var COLUMN_REST_END = "E";
var COLUMN_BACKGROUND_COLOR = "F";
var COLUMN_FONT_COLOR = "G";
var COLUMN_PICKUP1_START = "H";
var COLUMN_PICKUP1_END = "I";
var COLUMN_PICKUP2_START = "J";
var COLUMN_PICKUP2_END = "K";
var COLUMN_PICKUP3_START = "L";
var COLUMN_PICKUP3_END = "M";
var COLUMN_WEATHER_START = "N";
var COLUMN_WEATHER_END = "O";
var COLUMN_PICKWEATHER_START = "P";
var COLUMN_PICKWEATHER_END = "Q";
var COLUMN_NOD1_START = "R";
var COLUMN_NOD1_END = "S";
var COLUMN_NOD2_START = "T";
var COLUMN_NOD2_END = "U";
var COLUMN_REGION1_START = "V";
var COLUMN_REGION1_END = "W";
var COLUMN_REGION2_START = "X";
var COLUMN_REGION2_END = "Y";
var COLUMN_LEADER1_START = "Z";
var COLUMN_LEADER1_END = "AA";
var COLUMN_LEADER2_START = "AB";
var COLUMN_LEADER2_END = "AC";
var COLUMN_LINE1_START = "AD";
var COLUMN_LINE1_END = "AE";
var COLUMN_LINE2_START = "AF";
var COLUMN_LINE2_END = "AG";
var COLUMN_LINE3_START = "AH";
var COLUMN_LINE3_END = "AI";
var COLUMN_TOKUSHU1_START = "AJ";
var COLUMN_TOKUSHU1_END = "AK";
var COLUMN_TOKUSHU2_START = "AL";
var COLUMN_TOKUSHU2_END = "AM";

var INDEX_NAME = 0;
var INDEX_START = 1;
var INDEX_END = 2;
var INDEX_REST_START = 3;
var INDEX_REST_END = 4;
var INDEX_BACKGROUND_COLOR = 5;
var INDEX_FONT_COLOR = 6;
var INDEX_PICKUP1_START = 7;
var INDEX_PICKUP1_END = 8;
var INDEX_PICKUP2_START = 9;
var INDEX_PICKUP2_END = 10;
var INDEX_PICKUP3_START = 11;
var INDEX_PICKUP3_END = 12;
var INDEX_WEATHER_START = 13;
var INDEX_WEATHER_END = 14;
var INDEX_PICKWEATHER_START = 15;
var INDEX_PICKWEATHER_END = 16;
var INDEX_NOD1_START = 17;
var INDEX_NOD1_END = 18;
var INDEX_NOD2_START = 19;
var INDEX_NOD2_END = 20;
var INDEX_REGION1_START = 21;
var INDEX_REGION1_END = 22;
var INDEX_REGION2_START = 23;
var INDEX_REGION2_END = 24;
var INDEX_LEADER1_START = 25;
var INDEX_LEADER1_END = 26;
var INDEX_LEADER2_START = 27;
var INDEX_LEADER2_END = 28;
var INDEX_LINE1_START = 29;
var INDEX_LINE1_END = 30;
var INDEX_LINE2_START = 31;
var INDEX_LINE2_END = 32;
var INDEX_LINE3_START = 33;
var INDEX_LINE3_END = 34;
var INDEX_TOKUSHU1_START = 35;
var INDEX_TOKUSHU1_END = 36;
var INDEX_TOKUSHU2_START = 37;
var INDEX_TOKUSHU2_END = 38;

//var LABEL_POSITION = "BE4";
var LABEL_POSITION = "AW4";
var LABEL_WEEKDAY = "平日"
var LABEL_HOLIDAY = "休日"
var LABEL_PUBLIC_HOLIDAY = "祝日"

var COLOR_BLANK_BG = "#FFFFFF";
var COLOR_BLANK_FONT = "#000000";

//　＊＊＊＊＊＊＊＊＊＊＊
// 編集領域
// ＊＊＊＊＊＊＊＊＊＊＊
var COLUMN_INVALID_LINE = 51;
